apiVersion: v1
kind: Pod
metadata:
  name: ceph-pod-useX 
spec:
  containers:
  - name: ceph-busybox
    image: busybox          
    command: ["sleep", "6000000"]
    volumeMounts:
    - name: ceph-vol1       
      mountPath: /usr/share/busybox 
      readOnly: false
  volumes:
  - name: ceph-vol1         
    persistentVolumeClaim:
      claimName: ceph-claim-userX 
